2016-03-08 15:10:43 ERROR [pool-3-thread-1] org.apache.log4j.Logger.error(Logger.java:249) - org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.reflection.ReflectionException: There is no getter for property named 'orderId' in 'class org.bi.manage.app.bean.app.APPManageServerBean'
ExceptionStackTrace: ---------------start------------------------
	org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:75)
	org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:371)
	$Proxy9.insert(Unknown Source)
	org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:240)
	org.bi.manage.app.thread.APPMessageThread.registerAPP(APPMessageThread.java:223)
	org.bi.manage.app.thread.APPMessageThread.heartbeat(APPMessageThread.java:181)
	org.bi.manage.app.thread.APPMessageThread.run(APPMessageThread.java:58)
	org.bi.manage.app.dispatch.APPMonitor.MessageCallback(APPMonitor.java:209)
	org.bi.kafka.server.KafkaServerFixThread.run(KafkaServerFixThread.java:57)
	java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
	java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	java.util.concurrent.FutureTask.run(FutureTask.java:138)
	java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	java.lang.Thread.run(Thread.java:662)
ExceptionStackTrace: ---------------end------------------------

2016-03-08 15:24:14 ERROR [DefaultQuartzScheduler_Worker-1] org.apache.log4j.Logger.error(Logger.java:249) - java.lang.NullPointerException
ExceptionStackTrace: ---------------start------------------------
	org.bi.manage.app.job.AppMonitorJob.cleanDisCardAPP(AppMonitorJob.java:174)
	org.bi.manage.app.job.AppMonitorJob.updateAPPStatus(AppMonitorJob.java:147)
	org.bi.manage.app.job.AppMonitorJob.execute(AppMonitorJob.java:115)
	org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
ExceptionStackTrace: ---------------end------------------------

2016-03-08 15:24:14 ERROR [DefaultQuartzScheduler_Worker-1] org.apache.log4j.Logger.error(Logger.java:249) - java.lang.NullPointerException
ExceptionStackTrace: ---------------start------------------------
	org.bi.manage.app.job.AppMonitorJob.cleanDisCardAPP(AppMonitorJob.java:174)
	org.bi.manage.app.job.AppMonitorJob.updateAPPStatus(AppMonitorJob.java:147)
	org.bi.manage.app.job.AppMonitorJob.execute(AppMonitorJob.java:115)
	org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
ExceptionStackTrace: ---------------end------------------------

2016-03-08 15:24:48 ERROR [pool-7-thread-1] org.apache.log4j.Logger.error(Logger.java:249) - java.lang.ClassCastException: com.alibaba.fastjson.JSONObject cannot be cast to org.bi.bace.ETLBean
ExceptionStackTrace: ---------------start------------------------
	org.bi.manage.app.thread.APPMessageThread.updateAPPRunTask(APPMessageThread.java:95)
	org.bi.manage.app.thread.APPMessageThread.run(APPMessageThread.java:63)
	org.bi.manage.app.dispatch.APPMonitor.MessageCallback(APPMonitor.java:209)
	org.bi.kafka.server.KafkaServerFixThread.run(KafkaServerFixThread.java:57)
	java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
	java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	java.util.concurrent.FutureTask.run(FutureTask.java:138)
	java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	java.lang.Thread.run(Thread.java:662)
ExceptionStackTrace: ---------------end------------------------

2016-03-08 15:26:57 ERROR [pool-7-thread-1] org.apache.log4j.Logger.error(Logger.java:249) - java.lang.ClassCastException: com.alibaba.fastjson.JSONObject cannot be cast to org.bi.bace.ETLBean
ExceptionStackTrace: ---------------start------------------------
	org.bi.manage.app.thread.APPMessageThread.updateAPPRunTask(APPMessageThread.java:95)
	org.bi.manage.app.thread.APPMessageThread.run(APPMessageThread.java:63)
	org.bi.manage.app.dispatch.APPMonitor.MessageCallback(APPMonitor.java:209)
	org.bi.kafka.server.KafkaServerFixThread.run(KafkaServerFixThread.java:57)
	java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
	java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	java.util.concurrent.FutureTask.run(FutureTask.java:138)
	java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	java.lang.Thread.run(Thread.java:662)
ExceptionStackTrace: ---------------end------------------------

2016-03-08 15:29:27 ERROR [pool-7-thread-1] org.apache.log4j.Logger.error(Logger.java:249) - java.lang.ClassCastException: com.alibaba.fastjson.JSONObject cannot be cast to org.bi.bace.ETLBean
ExceptionStackTrace: ---------------start------------------------
	org.bi.manage.app.thread.APPMessageThread.updateAPPRunTask(APPMessageThread.java:95)
	org.bi.manage.app.thread.APPMessageThread.run(APPMessageThread.java:63)
	org.bi.manage.app.dispatch.APPMonitor.MessageCallback(APPMonitor.java:209)
	org.bi.kafka.server.KafkaServerFixThread.run(KafkaServerFixThread.java:57)
	java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
	java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	java.util.concurrent.FutureTask.run(FutureTask.java:138)
	java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	java.lang.Thread.run(Thread.java:662)
ExceptionStackTrace: ---------------end------------------------

2016-03-08 15:36:38 ERROR [pool-7-thread-1] org.apache.log4j.Logger.error(Logger.java:249) - java.lang.ClassCastException: com.alibaba.fastjson.JSONObject cannot be cast to org.bi.bace.ETLBean
ExceptionStackTrace: ---------------start------------------------
	org.bi.manage.app.thread.APPMessageThread.updateAPPRunTask(APPMessageThread.java:95)
	org.bi.manage.app.thread.APPMessageThread.run(APPMessageThread.java:63)
	org.bi.manage.app.dispatch.APPMonitor.MessageCallback(APPMonitor.java:209)
	org.bi.kafka.server.KafkaServerFixThread.run(KafkaServerFixThread.java:57)
	java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
	java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	java.util.concurrent.FutureTask.run(FutureTask.java:138)
	java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	java.lang.Thread.run(Thread.java:662)
ExceptionStackTrace: ---------------end------------------------

2016-03-08 15:41:58 ERROR [pool-7-thread-1] org.apache.log4j.Logger.error(Logger.java:249) - java.lang.ClassCastException: com.alibaba.fastjson.JSONObject cannot be cast to org.bi.bace.ETLBean
ExceptionStackTrace: ---------------start------------------------
	org.bi.manage.app.thread.APPMessageThread.updateAPPRunTask(APPMessageThread.java:95)
	org.bi.manage.app.thread.APPMessageThread.run(APPMessageThread.java:63)
	org.bi.manage.app.dispatch.APPMonitor.MessageCallback(APPMonitor.java:209)
	org.bi.kafka.server.KafkaServerFixThread.run(KafkaServerFixThread.java:57)
	java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
	java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	java.util.concurrent.FutureTask.run(FutureTask.java:138)
	java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	java.lang.Thread.run(Thread.java:662)
ExceptionStackTrace: ---------------end------------------------

2016-03-08 15:52:57 ERROR [pool-7-thread-1] org.apache.log4j.Logger.error(Logger.java:249) - java.lang.ClassCastException: com.alibaba.fastjson.JSONObject cannot be cast to org.bi.bace.ETLBean
ExceptionStackTrace: ---------------start------------------------
	org.bi.manage.app.thread.APPMessageThread.updateAPPRunTask(APPMessageThread.java:95)
	org.bi.manage.app.thread.APPMessageThread.run(APPMessageThread.java:63)
	org.bi.manage.app.dispatch.APPMonitor.MessageCallback(APPMonitor.java:209)
	org.bi.kafka.server.KafkaServerFixThread.run(KafkaServerFixThread.java:57)
	java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
	java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	java.util.concurrent.FutureTask.run(FutureTask.java:138)
	java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	java.lang.Thread.run(Thread.java:662)
ExceptionStackTrace: ---------------end------------------------

2016-03-08 15:57:38 ERROR [pool-7-thread-1] org.apache.log4j.Logger.error(Logger.java:249) - java.lang.ClassCastException: com.alibaba.fastjson.JSONObject cannot be cast to org.bi.bace.ETLBean
ExceptionStackTrace: ---------------start------------------------
	org.bi.manage.app.thread.APPMessageThread.updateAPPRunTask(APPMessageThread.java:95)
	org.bi.manage.app.thread.APPMessageThread.run(APPMessageThread.java:63)
	org.bi.manage.app.dispatch.APPMonitor.MessageCallback(APPMonitor.java:209)
	org.bi.kafka.server.KafkaServerFixThread.run(KafkaServerFixThread.java:57)
	java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
	java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	java.util.concurrent.FutureTask.run(FutureTask.java:138)
	java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	java.lang.Thread.run(Thread.java:662)
ExceptionStackTrace: ---------------end------------------------

2016-03-08 15:58:28 ERROR [pool-7-thread-1] org.apache.log4j.Logger.error(Logger.java:249) - java.lang.ClassCastException: com.alibaba.fastjson.JSONObject cannot be cast to org.bi.bace.ETLBean
ExceptionStackTrace: ---------------start------------------------
	org.bi.manage.app.thread.APPMessageThread.updateAPPRunTask(APPMessageThread.java:95)
	org.bi.manage.app.thread.APPMessageThread.run(APPMessageThread.java:63)
	org.bi.manage.app.dispatch.APPMonitor.MessageCallback(APPMonitor.java:209)
	org.bi.kafka.server.KafkaServerFixThread.run(KafkaServerFixThread.java:57)
	java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
	java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	java.util.concurrent.FutureTask.run(FutureTask.java:138)
	java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	java.lang.Thread.run(Thread.java:662)
ExceptionStackTrace: ---------------end------------------------

2016-03-08 16:03:27 ERROR [pool-7-thread-1] org.apache.log4j.Logger.error(Logger.java:249) - java.lang.ClassCastException: com.alibaba.fastjson.JSONObject cannot be cast to org.bi.bace.ETLBean
ExceptionStackTrace: ---------------start------------------------
	org.bi.manage.app.thread.APPMessageThread.updateAPPRunTask(APPMessageThread.java:95)
	org.bi.manage.app.thread.APPMessageThread.run(APPMessageThread.java:63)
	org.bi.manage.app.dispatch.APPMonitor.MessageCallback(APPMonitor.java:209)
	org.bi.kafka.server.KafkaServerFixThread.run(KafkaServerFixThread.java:57)
	java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
	java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	java.util.concurrent.FutureTask.run(FutureTask.java:138)
	java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	java.lang.Thread.run(Thread.java:662)
ExceptionStackTrace: ---------------end------------------------

2016-03-08 16:14:57 ERROR [pool-7-thread-1] org.apache.log4j.Logger.error(Logger.java:249) - java.lang.ClassCastException: com.alibaba.fastjson.JSONObject cannot be cast to org.bi.bace.ETLBean
ExceptionStackTrace: ---------------start------------------------
	org.bi.manage.app.thread.APPMessageThread.updateAPPRunTask(APPMessageThread.java:95)
	org.bi.manage.app.thread.APPMessageThread.run(APPMessageThread.java:63)
	org.bi.manage.app.dispatch.APPMonitor.MessageCallback(APPMonitor.java:209)
	org.bi.kafka.server.KafkaServerFixThread.run(KafkaServerFixThread.java:57)
	java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
	java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	java.util.concurrent.FutureTask.run(FutureTask.java:138)
	java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	java.lang.Thread.run(Thread.java:662)
ExceptionStackTrace: ---------------end------------------------

2016-03-08 16:21:10 ERROR [pool-7-thread-1] org.apache.log4j.Logger.error(Logger.java:249) - java.lang.NullPointerException
ExceptionStackTrace: ---------------start------------------------
	org.bi.manage.app.thread.APPMessageThread.updateAPPRunTask(APPMessageThread.java:116)
	org.bi.manage.app.thread.APPMessageThread.run(APPMessageThread.java:63)
	org.bi.manage.app.dispatch.APPMonitor.MessageCallback(APPMonitor.java:209)
	org.bi.kafka.server.KafkaServerFixThread.run(KafkaServerFixThread.java:57)
	java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
	java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	java.util.concurrent.FutureTask.run(FutureTask.java:138)
	java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	java.lang.Thread.run(Thread.java:662)
ExceptionStackTrace: ---------------end------------------------

2016-03-08 16:21:50 ERROR [pool-7-thread-1] org.apache.log4j.Logger.error(Logger.java:249) - java.lang.NullPointerException
ExceptionStackTrace: ---------------start------------------------
	org.bi.manage.app.thread.APPMessageThread.updateAPPRunTask(APPMessageThread.java:116)
	org.bi.manage.app.thread.APPMessageThread.run(APPMessageThread.java:63)
	org.bi.manage.app.dispatch.APPMonitor.MessageCallback(APPMonitor.java:209)
	org.bi.kafka.server.KafkaServerFixThread.run(KafkaServerFixThread.java:57)
	java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
	java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	java.util.concurrent.FutureTask.run(FutureTask.java:138)
	java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	java.lang.Thread.run(Thread.java:662)
ExceptionStackTrace: ---------------end------------------------

2016-03-08 18:33:28 ERROR [pool-3-thread-1] org.apache.log4j.Logger.error(Logger.java:249) - org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.reflection.ReflectionException: There is no getter for property named 'serverIp' in 'class org.bi.manage.app.bean.app.APPManageServerBean'
ExceptionStackTrace: ---------------start------------------------
	org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:75)
	org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:371)
	$Proxy9.insert(Unknown Source)
	org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:240)
	org.bi.manage.app.thread.APPMessageThread.registerAPP(APPMessageThread.java:237)
	org.bi.manage.app.thread.APPMessageThread.heartbeat(APPMessageThread.java:188)
	org.bi.manage.app.thread.APPMessageThread.run(APPMessageThread.java:58)
	org.bi.manage.app.dispatch.APPMonitor.MessageCallback(APPMonitor.java:200)
	org.bi.kafka.server.KafkaServerFixThread.run(KafkaServerFixThread.java:57)
	java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
	java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	java.util.concurrent.FutureTask.run(FutureTask.java:138)
	java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	java.lang.Thread.run(Thread.java:662)
ExceptionStackTrace: ---------------end------------------------

2016-03-08 19:04:02 ERROR [pool-3-thread-1] org.apache.log4j.Logger.error(Logger.java:249) - org.springframework.jdbc.BadSqlGrammarException: AppManageMapper.insertAPPServer (batch index #1) failed. Cause: java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status)
		values('BIAPP-8','2016-03-08 19:04:02',50,0,0,0,'1','1') was aborted.  Call getNextException to see the cause.
; bad SQL grammar []; nested exception is java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status)
		values('BIAPP-8','2016-03-08 19:04:02',50,0,0,0,'1','1') was aborted.  Call getNextException to see the cause.
ExceptionStackTrace: ---------------start------------------------
	org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:97)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
	org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:371)
	$Proxy9.insert(Unknown Source)
	org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:240)
	org.bi.manage.app.thread.APPMessageThread.registerAPP(APPMessageThread.java:234)
	org.bi.manage.app.thread.APPMessageThread.heartbeat(APPMessageThread.java:188)
	org.bi.manage.app.thread.APPMessageThread.run(APPMessageThread.java:58)
	org.bi.manage.app.dispatch.APPMonitor.MessageCallback(APPMonitor.java:200)
	org.bi.kafka.server.KafkaServerFixThread.run(KafkaServerFixThread.java:57)
	java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
	java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	java.util.concurrent.FutureTask.run(FutureTask.java:138)
	java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	java.lang.Thread.run(Thread.java:662)
ExceptionStackTrace: ---------------end------------------------

2016-03-08 19:04:53 ERROR [pool-3-thread-1] org.apache.log4j.Logger.error(Logger.java:249) - org.springframework.jdbc.BadSqlGrammarException: AppManageMapper.insertAPPServer (batch index #1) failed. Cause: java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status)
		values('BIAPP-8','2016-03-08 19:04:53',50,0,0,0,'1','1') was aborted.  Call getNextException to see the cause.
; bad SQL grammar []; nested exception is java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status)
		values('BIAPP-8','2016-03-08 19:04:53',50,0,0,0,'1','1') was aborted.  Call getNextException to see the cause.
ExceptionStackTrace: ---------------start------------------------
	org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:97)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
	org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:371)
	$Proxy9.insert(Unknown Source)
	org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:240)
	org.bi.manage.app.thread.APPMessageThread.registerAPP(APPMessageThread.java:234)
	org.bi.manage.app.thread.APPMessageThread.heartbeat(APPMessageThread.java:188)
	org.bi.manage.app.thread.APPMessageThread.run(APPMessageThread.java:58)
	org.bi.manage.app.dispatch.APPMonitor.MessageCallback(APPMonitor.java:200)
	org.bi.kafka.server.KafkaServerFixThread.run(KafkaServerFixThread.java:57)
	java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
	java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	java.util.concurrent.FutureTask.run(FutureTask.java:138)
	java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	java.lang.Thread.run(Thread.java:662)
ExceptionStackTrace: ---------------end------------------------

2016-03-08 19:05:53 ERROR [pool-3-thread-1] org.apache.log4j.Logger.error(Logger.java:249) - org.springframework.jdbc.BadSqlGrammarException: AppManageMapper.insertAPPServer (batch index #1) failed. Cause: java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status)
		values('BIAPP-8','2016-03-08 19:05:53',50,0,0,0,'1','1') was aborted.  Call getNextException to see the cause.
; bad SQL grammar []; nested exception is java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status)
		values('BIAPP-8','2016-03-08 19:05:53',50,0,0,0,'1','1') was aborted.  Call getNextException to see the cause.
ExceptionStackTrace: ---------------start------------------------
	org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:97)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
	org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:371)
	$Proxy9.insert(Unknown Source)
	org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:240)
	org.bi.manage.app.thread.APPMessageThread.registerAPP(APPMessageThread.java:234)
	org.bi.manage.app.thread.APPMessageThread.heartbeat(APPMessageThread.java:188)
	org.bi.manage.app.thread.APPMessageThread.run(APPMessageThread.java:58)
	org.bi.manage.app.dispatch.APPMonitor.MessageCallback(APPMonitor.java:200)
	org.bi.kafka.server.KafkaServerFixThread.run(KafkaServerFixThread.java:57)
	java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
	java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	java.util.concurrent.FutureTask.run(FutureTask.java:138)
	java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	java.lang.Thread.run(Thread.java:662)
ExceptionStackTrace: ---------------end------------------------

2016-03-08 19:06:53 ERROR [pool-3-thread-1] org.apache.log4j.Logger.error(Logger.java:249) - org.springframework.jdbc.BadSqlGrammarException: AppManageMapper.insertAPPServer (batch index #1) failed. Cause: java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status)
		values('BIAPP-8','2016-03-08 19:06:53',50,0,0,0,'1','1') was aborted.  Call getNextException to see the cause.
; bad SQL grammar []; nested exception is java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status)
		values('BIAPP-8','2016-03-08 19:06:53',50,0,0,0,'1','1') was aborted.  Call getNextException to see the cause.
ExceptionStackTrace: ---------------start------------------------
	org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:97)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
	org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:371)
	$Proxy9.insert(Unknown Source)
	org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:240)
	org.bi.manage.app.thread.APPMessageThread.registerAPP(APPMessageThread.java:234)
	org.bi.manage.app.thread.APPMessageThread.heartbeat(APPMessageThread.java:188)
	org.bi.manage.app.thread.APPMessageThread.run(APPMessageThread.java:58)
	org.bi.manage.app.dispatch.APPMonitor.MessageCallback(APPMonitor.java:200)
	org.bi.kafka.server.KafkaServerFixThread.run(KafkaServerFixThread.java:57)
	java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
	java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	java.util.concurrent.FutureTask.run(FutureTask.java:138)
	java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	java.lang.Thread.run(Thread.java:662)
ExceptionStackTrace: ---------------end------------------------

2016-03-08 19:07:53 ERROR [pool-3-thread-1] org.apache.log4j.Logger.error(Logger.java:249) - org.springframework.jdbc.BadSqlGrammarException: AppManageMapper.insertAPPServer (batch index #1) failed. Cause: java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status)
		values('BIAPP-8','2016-03-08 19:07:53',50,0,0,0,'1','1') was aborted.  Call getNextException to see the cause.
; bad SQL grammar []; nested exception is java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status)
		values('BIAPP-8','2016-03-08 19:07:53',50,0,0,0,'1','1') was aborted.  Call getNextException to see the cause.
ExceptionStackTrace: ---------------start------------------------
	org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:97)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
	org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:371)
	$Proxy9.insert(Unknown Source)
	org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:240)
	org.bi.manage.app.thread.APPMessageThread.registerAPP(APPMessageThread.java:234)
	org.bi.manage.app.thread.APPMessageThread.heartbeat(APPMessageThread.java:188)
	org.bi.manage.app.thread.APPMessageThread.run(APPMessageThread.java:58)
	org.bi.manage.app.dispatch.APPMonitor.MessageCallback(APPMonitor.java:200)
	org.bi.kafka.server.KafkaServerFixThread.run(KafkaServerFixThread.java:57)
	java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
	java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	java.util.concurrent.FutureTask.run(FutureTask.java:138)
	java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	java.lang.Thread.run(Thread.java:662)
ExceptionStackTrace: ---------------end------------------------

2016-03-08 19:08:53 ERROR [pool-3-thread-1] org.apache.log4j.Logger.error(Logger.java:249) - org.springframework.jdbc.BadSqlGrammarException: AppManageMapper.insertAPPServer (batch index #1) failed. Cause: java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status)
		values('BIAPP-8','2016-03-08 19:08:53',50,0,0,0,'1','1') was aborted.  Call getNextException to see the cause.
; bad SQL grammar []; nested exception is java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status)
		values('BIAPP-8','2016-03-08 19:08:53',50,0,0,0,'1','1') was aborted.  Call getNextException to see the cause.
ExceptionStackTrace: ---------------start------------------------
	org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:97)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
	org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:371)
	$Proxy9.insert(Unknown Source)
	org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:240)
	org.bi.manage.app.thread.APPMessageThread.registerAPP(APPMessageThread.java:234)
	org.bi.manage.app.thread.APPMessageThread.heartbeat(APPMessageThread.java:188)
	org.bi.manage.app.thread.APPMessageThread.run(APPMessageThread.java:58)
	org.bi.manage.app.dispatch.APPMonitor.MessageCallback(APPMonitor.java:200)
	org.bi.kafka.server.KafkaServerFixThread.run(KafkaServerFixThread.java:57)
	java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
	java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	java.util.concurrent.FutureTask.run(FutureTask.java:138)
	java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	java.lang.Thread.run(Thread.java:662)
ExceptionStackTrace: ---------------end------------------------

2016-03-08 19:09:53 ERROR [pool-3-thread-1] org.apache.log4j.Logger.error(Logger.java:249) - org.springframework.jdbc.BadSqlGrammarException: AppManageMapper.insertAPPServer (batch index #1) failed. Cause: java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status)
		values('BIAPP-8','2016-03-08 19:09:53',50,0,0,0,'1','1') was aborted.  Call getNextException to see the cause.
; bad SQL grammar []; nested exception is java.sql.BatchUpdateException: Batch entry 0 insert into bi.app_manage_server(server_id,register_time,
		task_num,task_run_num,task_succ_num,task_fail_num,server_status,dispatch_status)
		values('BIAPP-8','2016-03-08 19:09:53',50,0,0,0,'1','1') was aborted.  Call getNextException to see the cause.
ExceptionStackTrace: ---------------start------------------------
	org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:97)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
	org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:371)
	$Proxy9.insert(Unknown Source)
	org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:240)
	org.bi.manage.app.thread.APPMessageThread.registerAPP(APPMessageThread.java:234)
	org.bi.manage.app.thread.APPMessageThread.heartbeat(APPMessageThread.java:188)
	org.bi.manage.app.thread.APPMessageThread.run(APPMessageThread.java:58)
	org.bi.manage.app.dispatch.APPMonitor.MessageCallback(APPMonitor.java:200)
	org.bi.kafka.server.KafkaServerFixThread.run(KafkaServerFixThread.java:57)
	java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
	java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	java.util.concurrent.FutureTask.run(FutureTask.java:138)
	java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	java.lang.Thread.run(Thread.java:662)
ExceptionStackTrace: ---------------end------------------------

