2016-04-18 15:51:20 ERROR [DefaultQuartzScheduler_Worker-1] kafka.utils.Logging$class.error(Logging.scala:97) - Failed to collate messages by topic, partition due to: Failed to fetch topic metadata for topic: BIAPP-101
2016-04-18 15:51:20 ERROR [DefaultQuartzScheduler_Worker-1] kafka.utils.Logging$class.error(Logging.scala:97) - Failed to collate messages by topic, partition due to: Failed to fetch topic metadata for topic: BIAPP-101
2016-04-18 15:51:20 ERROR [DefaultQuartzScheduler_Worker-1] kafka.utils.Logging$class.error(Logging.scala:97) - Failed to collate messages by topic, partition due to: Failed to fetch topic metadata for topic: BIAPP-101
2016-04-18 15:51:20 ERROR [DefaultQuartzScheduler_Worker-1] kafka.utils.Logging$class.error(Logging.scala:97) - Failed to collate messages by topic, partition due to: Failed to fetch topic metadata for topic: BIAPP-101
2016-04-18 15:51:20 ERROR [DefaultQuartzScheduler_Worker-1] kafka.utils.Logging$class.error(Logging.scala:97) - Failed to send requests for topics BIAPP-101 with correlation ids in [0,8]
2016-04-18 15:51:20 ERROR [DefaultQuartzScheduler_Worker-1] org.apache.log4j.Logger.error(Logger.java:249) - kafka.common.FailedToSendMessageException: Failed to send messages after 3 tries.
ExceptionStackTrace: ---------------start------------------------
	kafka.producer.async.DefaultEventHandler.handle(DefaultEventHandler.scala:90)
	kafka.producer.Producer.send(Producer.scala:77)
	kafka.javaapi.producer.Producer.send(Producer.scala:33)
	org.bi.kafka.client.KafkaClient.sendMessage(KafkaClient.java:36)
	org.bi.manage.app.dispatch.DistributeMessage.start(DistributeMessage.java:87)
	org.bi.manage.app.dispatch.DistributeMessage.sendDataPacket(DistributeMessage.java:114)
	org.bi.manage.app.job.TableImportJob.execute(TableImportJob.java:55)
	org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
ExceptionStackTrace: ---------------end------------------------

2016-04-18 15:51:20 ERROR [DefaultQuartzScheduler_Worker-1] org.bi.manage.app.dispatch.DistributeMessage.start(DistributeMessage.java:96) - 调度服务编号[BIAPP-101]通讯失败,本次分发调度失败
2016-04-18 15:52:40 ERROR [DefaultQuartzScheduler_Worker-7] kafka.utils.Logging$class.error(Logging.scala:97) - Failed to collate messages by topic, partition due to: Failed to fetch topic metadata for topic: BIAPP-101
2016-04-18 15:52:40 ERROR [DefaultQuartzScheduler_Worker-7] kafka.utils.Logging$class.error(Logging.scala:97) - Failed to collate messages by topic, partition due to: Failed to fetch topic metadata for topic: BIAPP-101
2016-04-18 15:52:40 ERROR [DefaultQuartzScheduler_Worker-7] kafka.utils.Logging$class.error(Logging.scala:97) - Failed to collate messages by topic, partition due to: Failed to fetch topic metadata for topic: BIAPP-101
2016-04-18 15:52:40 ERROR [DefaultQuartzScheduler_Worker-7] kafka.utils.Logging$class.error(Logging.scala:97) - Failed to collate messages by topic, partition due to: Failed to fetch topic metadata for topic: BIAPP-101
2016-04-18 15:52:40 ERROR [DefaultQuartzScheduler_Worker-7] kafka.utils.Logging$class.error(Logging.scala:97) - Failed to send requests for topics BIAPP-101 with correlation ids in [0,8]
2016-04-18 15:52:40 ERROR [DefaultQuartzScheduler_Worker-7] org.apache.log4j.Logger.error(Logger.java:249) - kafka.common.FailedToSendMessageException: Failed to send messages after 3 tries.
ExceptionStackTrace: ---------------start------------------------
	kafka.producer.async.DefaultEventHandler.handle(DefaultEventHandler.scala:90)
	kafka.producer.Producer.send(Producer.scala:77)
	kafka.javaapi.producer.Producer.send(Producer.scala:33)
	org.bi.kafka.client.KafkaClient.sendMessage(KafkaClient.java:36)
	org.bi.manage.app.dispatch.DistributeMessage.start(DistributeMessage.java:87)
	org.bi.manage.app.dispatch.DistributeMessage.sendDataPacket(DistributeMessage.java:114)
	org.bi.manage.app.job.TableImportJob.execute(TableImportJob.java:55)
	org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
ExceptionStackTrace: ---------------end------------------------

2016-04-18 15:52:40 ERROR [DefaultQuartzScheduler_Worker-7] org.bi.manage.app.dispatch.DistributeMessage.start(DistributeMessage.java:96) - 调度服务编号[BIAPP-101]通讯失败,本次分发调度失败
2016-04-18 15:58:40 ERROR [DefaultQuartzScheduler_Worker-7] kafka.utils.Logging$class.error(Logging.scala:97) - Failed to collate messages by topic, partition due to: Failed to fetch topic metadata for topic: BIAPP-101
2016-04-18 15:58:40 ERROR [DefaultQuartzScheduler_Worker-7] kafka.utils.Logging$class.error(Logging.scala:97) - Failed to collate messages by topic, partition due to: Failed to fetch topic metadata for topic: BIAPP-101
2016-04-18 15:58:40 ERROR [DefaultQuartzScheduler_Worker-7] kafka.utils.Logging$class.error(Logging.scala:97) - Failed to collate messages by topic, partition due to: Failed to fetch topic metadata for topic: BIAPP-101
2016-04-18 15:58:40 ERROR [DefaultQuartzScheduler_Worker-7] kafka.utils.Logging$class.error(Logging.scala:97) - Failed to collate messages by topic, partition due to: Failed to fetch topic metadata for topic: BIAPP-101
2016-04-18 15:58:40 ERROR [DefaultQuartzScheduler_Worker-7] kafka.utils.Logging$class.error(Logging.scala:97) - Failed to send requests for topics BIAPP-101 with correlation ids in [0,8]
2016-04-18 15:58:40 ERROR [DefaultQuartzScheduler_Worker-7] org.apache.log4j.Logger.error(Logger.java:249) - kafka.common.FailedToSendMessageException: Failed to send messages after 3 tries.
ExceptionStackTrace: ---------------start------------------------
	kafka.producer.async.DefaultEventHandler.handle(DefaultEventHandler.scala:90)
	kafka.producer.Producer.send(Producer.scala:77)
	kafka.javaapi.producer.Producer.send(Producer.scala:33)
	org.bi.kafka.client.KafkaClient.sendMessage(KafkaClient.java:36)
	org.bi.manage.app.dispatch.DistributeMessage.start(DistributeMessage.java:87)
	org.bi.manage.app.dispatch.DistributeMessage.sendDataPacket(DistributeMessage.java:114)
	org.bi.manage.app.job.TableImportJob.execute(TableImportJob.java:55)
	org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
ExceptionStackTrace: ---------------end------------------------

2016-04-18 15:58:40 ERROR [DefaultQuartzScheduler_Worker-7] org.bi.manage.app.dispatch.DistributeMessage.start(DistributeMessage.java:96) - 调度服务编号[BIAPP-101]通讯失败,本次分发调度失败
2016-04-18 16:07:30 ERROR [DefaultQuartzScheduler_Worker-5] kafka.utils.Logging$class.error(Logging.scala:97) - Failed to collate messages by topic, partition due to: Failed to fetch topic metadata for topic: BIAPP-102
2016-04-18 16:07:30 ERROR [DefaultQuartzScheduler_Worker-5] kafka.utils.Logging$class.error(Logging.scala:97) - Failed to collate messages by topic, partition due to: Failed to fetch topic metadata for topic: BIAPP-102
2016-04-18 16:07:30 ERROR [DefaultQuartzScheduler_Worker-5] kafka.utils.Logging$class.error(Logging.scala:97) - Failed to collate messages by topic, partition due to: Failed to fetch topic metadata for topic: BIAPP-102
2016-04-18 16:07:30 ERROR [DefaultQuartzScheduler_Worker-5] kafka.utils.Logging$class.error(Logging.scala:97) - Failed to collate messages by topic, partition due to: Failed to fetch topic metadata for topic: BIAPP-102
2016-04-18 16:07:30 ERROR [DefaultQuartzScheduler_Worker-5] kafka.utils.Logging$class.error(Logging.scala:97) - Failed to send requests for topics BIAPP-102 with correlation ids in [0,8]
2016-04-18 16:07:30 ERROR [DefaultQuartzScheduler_Worker-5] org.apache.log4j.Logger.error(Logger.java:249) - kafka.common.FailedToSendMessageException: Failed to send messages after 3 tries.
ExceptionStackTrace: ---------------start------------------------
	kafka.producer.async.DefaultEventHandler.handle(DefaultEventHandler.scala:90)
	kafka.producer.Producer.send(Producer.scala:77)
	kafka.javaapi.producer.Producer.send(Producer.scala:33)
	org.bi.kafka.client.KafkaClient.sendMessage(KafkaClient.java:36)
	org.bi.manage.app.dispatch.DistributeMessage.start(DistributeMessage.java:87)
	org.bi.manage.app.dispatch.DistributeMessage.sendDataPacket(DistributeMessage.java:114)
	org.bi.manage.app.job.TableImportJob.execute(TableImportJob.java:55)
	org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
ExceptionStackTrace: ---------------end------------------------

2016-04-18 16:07:30 ERROR [DefaultQuartzScheduler_Worker-5] org.bi.manage.app.dispatch.DistributeMessage.start(DistributeMessage.java:96) - 调度服务编号[BIAPP-102]通讯失败,本次分发调度失败
2016-04-18 16:11:12 ERROR [GROUPID0_host-10-1-235-12-1460698963106-42204280_watcher_executor] kafka.utils.Logging$class.error(Logging.scala:103) - [GROUPID0_host-10-1-235-12-1460698963106-42204280], error during syncedRebalance
kafka.common.ConsumerRebalanceFailedException: GROUPID0_host-10-1-235-12-1460698963106-42204280 can't rebalance after 4 retries
	at kafka.consumer.ZookeeperConsumerConnector$ZKRebalancerListener.syncedRebalance(ZookeeperConsumerConnector.scala:633)
	at kafka.consumer.ZookeeperConsumerConnector$ZKRebalancerListener$$anon$1.run(ZookeeperConsumerConnector.scala:551)
2016-04-18 16:11:13 ERROR [GROUPID0_host-10-1-235-12-1460698962125-e9fa2fbd_watcher_executor] kafka.utils.Logging$class.error(Logging.scala:103) - [GROUPID0_host-10-1-235-12-1460698962125-e9fa2fbd], error during syncedRebalance
kafka.common.ConsumerRebalanceFailedException: GROUPID0_host-10-1-235-12-1460698962125-e9fa2fbd can't rebalance after 4 retries
	at kafka.consumer.ZookeeperConsumerConnector$ZKRebalancerListener.syncedRebalance(ZookeeperConsumerConnector.scala:633)
	at kafka.consumer.ZookeeperConsumerConnector$ZKRebalancerListener$$anon$1.run(ZookeeperConsumerConnector.scala:551)
2016-04-18 16:11:13 ERROR [GROUPID0_host-10-1-235-12-1460698962808-c42ff644_watcher_executor] kafka.utils.Logging$class.error(Logging.scala:103) - [GROUPID0_host-10-1-235-12-1460698962808-c42ff644], error during syncedRebalance
kafka.common.ConsumerRebalanceFailedException: GROUPID0_host-10-1-235-12-1460698962808-c42ff644 can't rebalance after 4 retries
	at kafka.consumer.ZookeeperConsumerConnector$ZKRebalancerListener.syncedRebalance(ZookeeperConsumerConnector.scala:633)
	at kafka.consumer.ZookeeperConsumerConnector$ZKRebalancerListener$$anon$1.run(ZookeeperConsumerConnector.scala:551)
2016-04-18 16:11:20 ERROR [GROUPID0_host-10-1-235-12-1460698963106-42204280_watcher_executor] kafka.utils.Logging$class.error(Logging.scala:103) - [GROUPID0_host-10-1-235-12-1460698963106-42204280], error during syncedRebalance
kafka.common.ConsumerRebalanceFailedException: GROUPID0_host-10-1-235-12-1460698963106-42204280 can't rebalance after 4 retries
	at kafka.consumer.ZookeeperConsumerConnector$ZKRebalancerListener.syncedRebalance(ZookeeperConsumerConnector.scala:633)
	at kafka.consumer.ZookeeperConsumerConnector$ZKRebalancerListener$$anon$1.run(ZookeeperConsumerConnector.scala:551)
2016-04-18 16:11:21 ERROR [GROUPID0_host-10-1-235-12-1460698962125-e9fa2fbd_watcher_executor] kafka.utils.Logging$class.error(Logging.scala:103) - [GROUPID0_host-10-1-235-12-1460698962125-e9fa2fbd], error during syncedRebalance
kafka.common.ConsumerRebalanceFailedException: GROUPID0_host-10-1-235-12-1460698962125-e9fa2fbd can't rebalance after 4 retries
	at kafka.consumer.ZookeeperConsumerConnector$ZKRebalancerListener.syncedRebalance(ZookeeperConsumerConnector.scala:633)
	at kafka.consumer.ZookeeperConsumerConnector$ZKRebalancerListener$$anon$1.run(ZookeeperConsumerConnector.scala:551)
2016-04-18 16:12:00 ERROR [GROUPID0_host-10-1-235-12-1460698962125-e9fa2fbd_watcher_executor] kafka.utils.Logging$class.error(Logging.scala:103) - [GROUPID0_host-10-1-235-12-1460698962125-e9fa2fbd], error during syncedRebalance
kafka.common.ConsumerRebalanceFailedException: GROUPID0_host-10-1-235-12-1460698962125-e9fa2fbd can't rebalance after 4 retries
	at kafka.consumer.ZookeeperConsumerConnector$ZKRebalancerListener.syncedRebalance(ZookeeperConsumerConnector.scala:633)
	at kafka.consumer.ZookeeperConsumerConnector$ZKRebalancerListener$$anon$1.run(ZookeeperConsumerConnector.scala:551)
2016-04-18 16:15:49 ERROR [DefaultQuartzScheduler_Worker-3] org.apache.log4j.Logger.error(Logger.java:261) - 获取Redis中的值时出现异常：com.alibaba.fastjson.JSONException: syntax error, expect {, actual EOF, pos 0
ExceptionStackTrace: ---------------start------------------------
	com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:232)
	com.alibaba.fastjson.parser.deserializer.ASMJavaBeanDeserializer.parseRest(ASMJavaBeanDeserializer.java:100)
	Fastjson_ASM_APPManageServerBean_1.deserialze(Unknown Source)
	com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:551)
	com.alibaba.fastjson.JSON.parseObject(JSON.java:250)
	com.alibaba.fastjson.JSON.parseObject(JSON.java:226)
	com.alibaba.fastjson.JSON.parseObject(JSON.java:185)
	com.alibaba.fastjson.JSON.parseObject(JSON.java:303)
	org.bi.redis.RedisManage.getList(RedisManage.java:444)
	org.bi.redis.RedisManage.getList(RedisManage.java:392)
	org.bi.manage.app.job.AppMonitorJob.execute(AppMonitorJob.java:52)
	org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
ExceptionStackTrace: ---------------end------------------------

2016-04-18 16:16:49 ERROR [DefaultQuartzScheduler_Worker-8] org.apache.log4j.Logger.error(Logger.java:261) - 获取Redis中的值时出现异常：com.alibaba.fastjson.JSONException: syntax error, expect {, actual EOF, pos 0
ExceptionStackTrace: ---------------start------------------------
	com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:232)
	com.alibaba.fastjson.parser.deserializer.ASMJavaBeanDeserializer.parseRest(ASMJavaBeanDeserializer.java:100)
	Fastjson_ASM_APPManageServerBean_1.deserialze(Unknown Source)
	com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:551)
	com.alibaba.fastjson.JSON.parseObject(JSON.java:250)
	com.alibaba.fastjson.JSON.parseObject(JSON.java:226)
	com.alibaba.fastjson.JSON.parseObject(JSON.java:185)
	com.alibaba.fastjson.JSON.parseObject(JSON.java:303)
	org.bi.redis.RedisManage.getList(RedisManage.java:444)
	org.bi.redis.RedisManage.getList(RedisManage.java:392)
	org.bi.manage.app.job.AppMonitorJob.execute(AppMonitorJob.java:52)
	org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
ExceptionStackTrace: ---------------end------------------------

2016-04-18 16:17:49 ERROR [DefaultQuartzScheduler_Worker-3] org.apache.log4j.Logger.error(Logger.java:261) - 获取Redis中的值时出现异常：com.alibaba.fastjson.JSONException: syntax error, expect {, actual EOF, pos 0
ExceptionStackTrace: ---------------start------------------------
	com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:232)
	com.alibaba.fastjson.parser.deserializer.ASMJavaBeanDeserializer.parseRest(ASMJavaBeanDeserializer.java:100)
	Fastjson_ASM_APPManageServerBean_1.deserialze(Unknown Source)
	com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:551)
	com.alibaba.fastjson.JSON.parseObject(JSON.java:250)
	com.alibaba.fastjson.JSON.parseObject(JSON.java:226)
	com.alibaba.fastjson.JSON.parseObject(JSON.java:185)
	com.alibaba.fastjson.JSON.parseObject(JSON.java:303)
	org.bi.redis.RedisManage.getList(RedisManage.java:444)
	org.bi.redis.RedisManage.getList(RedisManage.java:392)
	org.bi.manage.app.job.AppMonitorJob.execute(AppMonitorJob.java:52)
	org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
ExceptionStackTrace: ---------------end------------------------

2016-04-18 16:24:13 ERROR [pool-3-thread-1] org.apache.log4j.Logger.error(Logger.java:261) - 获取Redis中的值时出现异常：com.alibaba.fastjson.JSONException: syntax error, expect {, actual EOF, pos 0
ExceptionStackTrace: ---------------start------------------------
	com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:232)
	com.alibaba.fastjson.parser.deserializer.ASMJavaBeanDeserializer.parseRest(ASMJavaBeanDeserializer.java:100)
	Fastjson_ASM_APPManageServerBean_1.deserialze(Unknown Source)
	com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:551)
	com.alibaba.fastjson.JSON.parseObject(JSON.java:250)
	com.alibaba.fastjson.JSON.parseObject(JSON.java:226)
	com.alibaba.fastjson.JSON.parseObject(JSON.java:185)
	com.alibaba.fastjson.JSON.parseObject(JSON.java:303)
	org.bi.redis.RedisManage.getList(RedisManage.java:444)
	org.bi.redis.RedisManage.getList(RedisManage.java:392)
	org.bi.manage.app.thread.APPMessageThread.heartbeat(APPMessageThread.java:163)
	org.bi.manage.app.thread.APPMessageThread.run(APPMessageThread.java:58)
	org.bi.manage.app.dispatch.APPMonitor.MessageCallback(APPMonitor.java:250)
	org.bi.kafka.server.KafkaServerFixThread.run(KafkaServerFixThread.java:57)
	java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
	java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	java.util.concurrent.FutureTask.run(FutureTask.java:138)
	java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	java.lang.Thread.run(Thread.java:662)
ExceptionStackTrace: ---------------end------------------------

2016-04-18 17:38:31 ERROR [http-bio-10008-exec-7] org.apache.log4j.Logger.error(Logger.java:249) - org.springframework.dao.DataIntegrityViolationException: AnalysisMapper.insertOutliner (batch index #1) failed. Cause: java.sql.BatchUpdateException: Batch entry 0 insert into bi.report_outliner(report_id) values (NULL) was aborted.  Call getNextException to see the cause.
; SQL []; ERROR: null value in column "report_id" violates not-null constraint
  Detail: Failing row contains (null, null, 0, 0).; nested exception is org.postgresql.util.PSQLException: ERROR: null value in column "report_id" violates not-null constraint
  Detail: Failing row contains (null, null, 0, 0).
ExceptionStackTrace: ---------------start------------------------
	org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:249)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
	org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:371)
	$Proxy9.insert(Unknown Source)
	org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:240)
	org.bi.platform.service.myreport.module.AnalysisModule.recordVisit(AnalysisModule.java:424)
	org.bi.platform.service.myhome.controller.MyHomeController.recordVisit(MyHomeController.java:93)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	java.lang.reflect.Method.invoke(Method.java:597)
	org.springframework.web.method.support.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:215)
	org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:132)
	org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104)
	org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:745)
	org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:686)
	org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:80)
	org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:925)
	org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:856)
	org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:953)
	org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:855)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
	org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:829)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	com.radiadesign.catalina.session.RedisSessionHandlerValve.invoke(RedisSessionHandlerValve.java:26)
	org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
	org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
	org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
	org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
	org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
	java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	java.lang.Thread.run(Thread.java:662)
ExceptionStackTrace: ---------------end------------------------

2016-04-18 20:47:27 ERROR [pool-3-thread-1] org.apache.log4j.Logger.error(Logger.java:261) - 获取Redis中的值时出现异常：redis.clients.jedis.exceptions.JedisDataException: ERR no such key
ExceptionStackTrace: ---------------start------------------------
	redis.clients.jedis.Protocol.processError(Protocol.java:117)
	redis.clients.jedis.Protocol.process(Protocol.java:151)
	redis.clients.jedis.Protocol.read(Protocol.java:205)
	redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:297)
	redis.clients.jedis.Connection.getStatusCodeReply(Connection.java:196)
	redis.clients.jedis.Jedis.lset(Jedis.java:957)
	org.bi.redis.RedisManage.modList(RedisManage.java:801)
	org.bi.manage.app.thread.APPMessageThread.heartbeat(APPMessageThread.java:182)
	org.bi.manage.app.thread.APPMessageThread.run(APPMessageThread.java:58)
	org.bi.manage.app.dispatch.APPMonitor.MessageCallback(APPMonitor.java:250)
	org.bi.kafka.server.KafkaServerFixThread.run(KafkaServerFixThread.java:57)
	java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
	java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	java.util.concurrent.FutureTask.run(FutureTask.java:138)
	java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	java.lang.Thread.run(Thread.java:662)
ExceptionStackTrace: ---------------end------------------------

